language: ruby
cache: bundler

services:
  - postgresql
  - mysql
before_script:
  - psql -c 'create database geocoder_test;' -U postgres

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

env:
  global: 
    - JRUBY_OPTS=--2.0
  matrix:
    - DB=
    - DB=sqlite
    - DB=sqlite USE_SQLITE_EXT=1
    - DB=postgres
    - DB=mysql
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-19mode
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails5.0
matrix:
  exclude:
    - env: DB=
      gemfile: gemfiles/Gemfile.rails5.0
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails5.0
    - env: DB=sqlite USE_SQLITE_EXT=1
      rvm: jruby-19mode
